### ISSUE TITLE
Objectbridge is not compatible to Pimcore 5.6

### ISSUE THREAD

**Issue by jorisros** [YouweGit/PimcoreObjectBridge#22]

**Comment by semrahakan** [comment]
Upgrading Pimcore from 5.4 to 5.6 was successful.
You are also successfull to create objects of car and garage car.
The problem is related to database when you create object of garage.
The screenshot is provided below.
<img width="708" alt="screen shot 2019-02-01 at 15 40 31" src="https://user-images.githubusercontent.com/21988693/52129900-0c212180-2639-11e9-9550-1d9a9b346c09.png">

**Comment by jorisros** [comment]
Has been related to: https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/index.html#page_Version-5-6-0

**Comment by jorisros** [comment]
Solved in pull request #28
