### ISSUE TITLE
Status of this Bundle

### ISSUE THREAD

**Issue by dpfaffenbauer** [YouweGit/PimcoreObjectBridge#7]
This Bundle is exactly what I need for a Project and maybe also for CoreShop.

I wanted to ask you if this is actually maintained and used? Otherwise I would fork it into CoreShop's PimcoreBundle which already adds a lot of useful stuff to Pimcore.

**Comment by dpfaffenbauer** [comment]
Ok, after a closer look: The current version does not work, it uses for example \Zend_Registry. Still an easy fix to get it running and it looks like this:

![bildschirmfoto 2018-05-18 um 13 05 04](https://user-images.githubusercontent.com/5981845/40231627-1a2e6058-5a9c-11e8-9306-5f5b3eed4d0c.png)

I would still love to overtake this and refactor it, I would also change the UI and make it way more appealing, the current version is very similar to `multihref with metadata`, my Idea would look a bit more like that:

![tour-refactor-v2](https://user-images.githubusercontent.com/5981845/40231584-f29574aa-5a9b-11e8-89e1-b5195baa6c6d.png)


BTW: Screenshot is not 100% accurate -> I just moved and sliced things together in Photoshop

**Comment by jorisros** [comment]
Hi @dpfaffenbauer,

Yes this bundle is used actively inside Youwe projects. 

I really like your screenshot about the improvement, we now use the objectbridge mostly for overviews of relations and add values on relation, but I subscribe to the idea to have more functionality in the way of subforms. Because at the moment we getting often problems with the amount of fields.

My suggestion would be that we make a list/form display toggle so you can choose between those display modes.

**Comment by dpfaffenbauer** [comment]
Hi,

This is what I came up with so far:

https://github.com/coreshop/CoreShop/pull/449
